
POST http://localhost:8080/api/users
Content-Type: application/json

{
    "username": "Pa_dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd",
    "passwordHash": "afsefsefsefsef"
}

